export enum RouteE {
    Home = '.',
    ArgoCD = '?route=argo-cd',
    Ansible = '?route=ansible',
    Application = '?route=application',
    Cluster = '?route=cluster',
    Credentials = '?route=credentials',
    Placement = '?route=placement',
    Policy = '?route=policy',
    PolicySet = '?route=policy-set',
    CreatePolicySet = '?route=create-policy-set',
    EditPolicySet1 = '?route=edit-policy-set-1',
    EditPolicySet2 = '?route=edit-policy-set-2',
    EditPolicySet3 = '?route=edit-policy-set-3',
    EditPolicySet4 = '?route=edit-policy-set-4',
    EditPolicySet5 = '?route=edit-policy-set-5',
    EditPolicySet6 = '?route=edit-policy-set-6',
    EditPolicySet7 = '?route=edit-policy-set-7',
    EditPolicySet8 = '?route=edit-policy-set-8',
    ROSA = '?route=rosa',
    App = '?route=app',
    Inputs = '?route=inputs',
    Wizards = '?route=wizards',
}
