export enum RouteE {
    Home = '.',
    ArgoCD = '?route=argo-cd',
    Ansible = '?route=ansible',
    Application = '?route=application',
    Cluster = '?route=cluster',
    Credentials = '?route=credentials',
    Placement = '?route=placement',
    Policy = '?route=policy',
    PolicySet = '?route=policy-set',
    ROSA = '?route=rosa',
    App = '?route=app',
    Inputs = '?route=inputs',
    Wizards = '?route=wizards',
}
